import Veda.Core.Design

/-!
# Traces

A `Trace D` assigns to every clock tick `n` the design state and the module
inputs at that tick. `Trace.valid` singles out the traces the hardware can
actually exhibit: the initial state satisfies `init` and consecutive states
are related by `step`. Temporal properties (Veda/Ltl) are interpreted over
valid traces.

Traces are infinite (`Nat`-indexed) — this is the semantic basis for
*unbounded* verification, in contrast to bounded model checking.
-/

namespace Veda

/-- An infinite trace of design `D`: state and input at every clock tick. -/
def Trace (D : Design) : Type := Nat → D.StateTy × D.InputTy

namespace Trace

variable {D : Design}

/-- The design state at tick `n`. -/
def state (t : Trace D) (n : Nat) : D.StateTy := (t n).1

/-- The module inputs at tick `n`. -/
def input (t : Trace D) (n : Nat) : D.InputTy := (t n).2

/-- A trace is valid iff it starts in a legal reset state and follows the
transition function at every tick. -/
def valid (D : Design) (t : Trace D) : Prop :=
  D.init (t.state 0) ∧ ∀ n, t.state (n + 1) = D.step (t.state n) (t.input n)

/-- Build the unique trace generated by initial state `s0` and input
stream `ins`. -/
def ofInputs (D : Design) (s0 : D.StateTy) (ins : Nat → D.InputTy) : Trace D :=
  fun n => (D.run s0 ins n, ins n)

@[simp] theorem ofInputs_state (D : Design) (s0 : D.StateTy)
    (ins : Nat → D.InputTy) (n : Nat) :
    (ofInputs D s0 ins).state n = D.run s0 ins n := rfl

@[simp] theorem ofInputs_input (D : Design) (s0 : D.StateTy)
    (ins : Nat → D.InputTy) (n : Nat) :
    (ofInputs D s0 ins).input n = ins n := rfl

/-- The generated trace is valid whenever the seed state is legal. -/
theorem ofInputs_valid (D : Design) (s0 : D.StateTy) (ins : Nat → D.InputTy)
    (h : D.init s0) : valid D (ofInputs D s0 ins) :=
  ⟨h, fun _ => rfl⟩

/-- Determinism: a valid trace is pointwise determined by its initial state
and its input stream. This is what lets the executable simulator stand in
for the semantics in the differential harness. -/
theorem valid_state_eq_run (t : Trace D) (h : valid D t) (n : Nat) :
    t.state n = D.run (t.state 0) (fun k => t.input k) n := by
  induction n with
  | zero => rfl
  | succ n ih => rw [h.2 n, ih]; rfl

/-- Every valid trace is of the form `ofInputs`. -/
theorem valid_iff_exists_ofInputs (t : Trace D) :
    valid D t ↔ ∃ s0 ins, D.init s0 ∧ ∀ n,
      t.state n = (ofInputs D s0 ins).state n ∧
      t.input n = (ofInputs D s0 ins).input n := by
  constructor
  · intro h
    exact ⟨t.state 0, fun k => t.input k, h.1,
      fun n => ⟨valid_state_eq_run t h n, rfl⟩⟩
  · rintro ⟨s0, ins, hinit, hpt⟩
    constructor
    · rw [(hpt 0).1]; exact hinit
    · intro n
      rw [(hpt (n + 1)).1, (hpt n).1, (hpt n).2]
      rfl

end Trace

end Veda
